### ISSUE TITLE
👓Cool Project: Nicely Done so far 👏👏

### ISSUE THREAD

**Issue by digitekh2i** [Berabjesus/Newsweek.com-clone#1]
with reference to the original page :

- on completion of your project, study the scroll down page behavior of the original page...it gets to a point that only the extreme left column content will be moving. 

- Not mobile responsive yet: you can use the bootstrap classes suggested by the team members...small, medium, large and also columns. whichever that suits your goal.

- News form yet to be completed..?

- Bootstrap rows and columns not implemented on some fields.

In all...you're on way🦾

**Comment by Berabjesus** [comment]
All fixed !! Thanks !
